[tool.poetry]
name = "web-page"
version = "0.1.0"
description = ""
authors = ["Kiniaka <147816937+Kiniaka@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
